POST http://localhost:3003/api/blogs/
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik9vbmFUYXgiLCJpZCI6IjZhMTgyOGE1NDIyMzYwOTFiNjk5ZmUwZiIsImlhdCI6MTc3OTk3MDQ3M30.b0-xEFhDbp9Zf6pEFNjtbZ1AzTUmnG3h_R4xejWfiV4

{
    "title": "Adventures of Oona Tax",
    "author": "Oona Tax",
    "url": "https://www.oonatax.com",
    "likes": 37
}