POST http://localhost:3001/api/notes
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkVsdmlzIiwiaWQiOiI2YTE0NTBlNTAyZTVlZjI5ZWNlNzBmNWUiLCJpYXQiOjE3Nzk4NzU1Njh9.f_tdy-cCizWlz0OCyAybcbAalspq4SsMH9h1dY_u0gU

{
    "content": "Pufffffffff",
    "important": true
}